$(function() {
	/*活跃度charts*/
			$('#q-month-table').highcharts({
				chart:{
					type:'column'
				},
				title:{
					text:"本月活跃度"
				},
				xAxis:{
					categories:['内科','外科','牙科','其它']
				},
				yAxis:{
					title:{
						text:'数量'
					}
				},
				series:[{
					name:'问题咨询',
					data:[100,300,40,400]
				},{
					name:'资料上传',
					data:[50,30,14,100]
				}]
			});
			$('#q-week-table').highcharts({
				chart:{
					type:'column'
				},
				title:{
					text:"本周活跃度"
				},
				xAxis:{
					categories:['内科','外科','牙科','其它']
				},
				yAxis:{
					title:{
						text:'数量'
					}
				},
				series:[{
					name:'问题咨询',
					data:[70,30,40,60]
				},{
					name:'资料上传',
					data:[100,30,80,10]
				}]
			});
			$('#q-day-table').highcharts({
				chart:{
					type:'column'
				},
				title:{
					text:"本日活跃度"
				},
				xAxis:{
					categories:['内科','外科','牙科','其它']
				},
				yAxis:{
					title:{
						text:'数量'
					}
				},
				series:[{
					name:'问题咨询',
					data:[5,10,1,20]
				},{
					name:'资料上传',
					data:[9,3,5,30]
				}]
			});
	/*英雄榜chart*/
			$('#h-month-table').highcharts({
				chart:{
					type:'column'
				},
				title:{
					text:"本月雷锋榜"
				},
				xAxis:{
					categories:['糖糖','z-O','Single','赵医生','雨上']
				},
				yAxis:{
					title:{
						text:'数量'
					}
				},
				series:[{
					name:'解答问题',
					data:[160,140,100,52,67]
				},{
					name:'资料上传',
					data:[100,30,120,40,23]
				}],
				colors:['#6A1CD4','#44C42B']
			});
			$('#h-week-table').highcharts({
				chart:{
					type:'column'
				},
				title:{
					text:"本周雷锋榜"
				},
				xAxis:{
					categories:['小鱼','JY','糖糖','二龙','Mint']
				},
				yAxis:{
					title:{
						text:'数量'
					}
				},
				series:[{
					name:'解答问题',
					data:[50,30,10,26,18]
				},{
					name:'资料上传',
					data:[10,13,20,5,3]
				}],
				colors:['#6A1CD4','#44C42B']
			});
			$('#h-day-table').highcharts({
				chart:{
					type:'column'
				},
				title:{
					text:"本日雷锋榜"
				},
				xAxis:{
					categories:['kko','凯西','六便士','边锋']
				},
				yAxis:{
					title:{
						text:'数量'
					}
				},
				series:[{
					name:'解答问题',
					data:[5,10,4,6,3]
				},{
					name:'资料上传',
					data:[9,3,5,0,2]
				}],
				colors:['#6A1CD4','#44C42B']
			});
		});